### ISSUE TITLE
MIUIVerificationCode.pattern

### ISSUE THREAD

**Issue by actionbar** [gitaiQAQ/SMSCodeHelper#1]
What is MIUIVerificationCode.pattern, is what language

**Comment by GitaiQAQ** [comment]
[Backus normal form](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form)

**Comment by actionbar** [comment]
@GitaiQAQ Hello there! In the **Android** **backus normal form** with what compiler / parser to use?

**Comment by GitaiQAQ** [comment]
In MIUI, pattern file used for Natural Language Processing (NLP).  

[VerificationCodeRecognition.java](https://github.com/GitaiQAQ/SMSCodeHelper/blob/cda7ef2d61a7c2150a833e7c4dc1b852902f2e8b/Decompilation/MIUI/src_cfr/com/xiaomi/smsunderstand/task/VerificationCodeRecognition.java#L119-L123)

```java 
new com.xiaomi.nlp.Parser(String.valueOf((Object)SMSUnderstand.dictionaryPath) + "/patterns/VerificationCode.pattern")
```

[Parser.java](https://github.com/GitaiQAQ/SMSCodeHelper/blob/cda7ef2d61a7c2150a833e7c4dc1b852902f2e8b/Decompilation/MIUI/src_cfr/com/xiaomi/nlp/Parser.java)

Search keywords "NLP" and "BNF"

**Comment by actionbar** [comment]
OK Thank you!
